version: '3'
services:
  redis-server:
    image: 'redis'
    ports:
      - '6379:6379'
    networks:
      - my-network
  node-app:
    build: .
    ports:
      - "4001:8081"
    networks:
      - my-network
networks:
  my-network:
