version: '3.8'

services:

  postgres-init:
    image: postgres:latest
    command: [ "bash", "-c", "sleep 10 && psql -U dbuser -c 'CREATE DATABASE mydb;' && psql -U dbuser -c 'GRANT ALL PRIVILEGES ON DATABASE app_mydb TO dbuser;'" ]
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - initexample

  postgres:
    image: postgres:latest #postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "mydb", "-U", "dbuser", "-p","a" ]
      timeout: 45s
      interval: 10s
      retries: 3
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    networks:
      - initexample
#  metabase:
#    image: metabase/metabase:latest
#    depends_on:
#      - postgres
#    ports:
#      - 3000:3000
#    networks:
#      - initexample

networks:
  initexample:
    driver: bridge