version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nitinkc/simple-react-frontend:latest
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
