FROM busybox

# Using CMD
CMD ["echo", "Hello, CMD! - this can be overridden \n"]

# Using ENTRYPOINT
ENTRYPOINT ["echo", "Hello, ENTRYPOINT! - This will always execute while starting the container \n"]