version: '3'
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      - redis-server
    networks:
      - my-network

  redis-server: #This is the server name that goes in config : new Jedis("redis-server", 6379);
    image: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
